apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: acme-corp
  description: The acme-corp organization
  links:
    - url: http://www.acme.com/
      title: Website
    - url: https://meta.wikimedia.org/wiki/
      title: Intranet
spec:
  type: organization
  profile:
    displayName: ACME Corp
    email: info@example.com
    picture: https://api.dicebear.com/7.x/identicon/svg?seed=Maggie&flip=true&backgroundColor=ffdfbf
  children: [infrastructure]
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: example-groups
  description: A collection of all Backstage example Groups
spec:
  targets:
    - ./infrastructure-group.yaml
    - ./boxoffice-group.yaml
    - ./backstage-group.yaml
    - ./team-a-group.yaml
    - ./team-b-group.yaml
    - ./team-c-group.yaml
    - ./team-d-group.yaml
    - ./robert-test.yaml
---
# apiVersion: backstage.io/v1alpha1
# kind: User
# metadata:
#   name: robert.wlodarczyk # This should match either the local part of the email or a resolver configuration
# spec:
#   profile:
#     displayName: Robert Wlodarczyk [EXT] # Matches the "Display name" from Entra ID
#     email: robert.wlodarczyk@pl.abb.com # Matches the "User principal name" or "Mail"
#   memberOf:
#     - robert-test