name: Deploy Storage Account

on:
  workflow_dispatch:
    inputs:
      storageAccountName:
        description: 'Name of the storage account'
        required: true
        default: ''
      subscription:
        description: 'Azure subscription ID'
        required: true
        default: ''
      resourceGroupName:
        description: 'Name of the resource group'
        required: true
        default: ''
      location:
        description: 'Location for the resources'
        required: true
        default: ''
      sku:
        description: 'SKU for the storage account'
        required: false
        default: 'Standard_LRS'

env:
  AZURE_CLIENT_ID: 89117763-b5d3-44d5-aad6-037988812fa8
  AZURE_TENANT_ID: 372ee9e0-9ce0-4033-a64a-c07073a91ecd
  AZURE_CLIENT_SECRET: U0_8Q~fo5~0BdyrLYKsTHO-Ls2x5N.sABL3k1c.x

jobs:
  deploy-storage-account:
    name: Deploy Storage Account
    runs-on: ubuntu-latest
    env:
      STORAGE_ACCOUNT_NAME: ${{ github.event.inputs.storageAccountName }}
      AZURE_SUBSCRIPTION: ${{ github.event.inputs.subscription }}
      RESOURCE_GROUP_NAME: ${{ github.event.inputs.resourceGroupName }}
      LOCATION: ${{ github.event.inputs.location }}
      SKU: ${{ github.event.inputs.sku }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ env.AZURE_CLIENT_ID }}
        tenant-id: ${{ env.AZURE_TENANT_ID }}
        client-secret: ${{ env.AZURE_CLIENT_SECRET }}

    - name: Set Azure subscription
      run: |
        az account set --subscription $AZURE_SUBSCRIPTION

    - name: Create resource group
      run: |
        az group create --name $RESOURCE_GROUP_NAME --location $LOCATION

    - name: Create storage account
      run: |
        az storage account create \
          --resource-group $RESOURCE_GROUP_NAME \
          --name $STORAGE_ACCOUNT_NAME \
          --sku $SKU \
          --encryption-services blob \
          --allow-blob-public-access false \
          --min-tls-version TLS1_2 \
          --default-action Deny \
          --bypass AzureServices
